modLoader = "javafml"
loaderVersion = "[9,)"
issueTrackerURL = "https://github.com/Etern-34520/MusicHud/issues"
license = "LGPL-3.0"

[[mods]]
modId = "music_hud"
version = "${version}"
displayName = "Music Hud"
authors = "Etern"
description = "A mod allow to play music from NCM in whole server "
displayURL = "https://github.com/Etern-34520/MusicHud"
logoFile = "assets/music_hud/icon.png"

[[dependencies.music_hud]]
modId = "neoforge"
type = "required"
versionRange = "[21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.music_hud]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.music_hud]]
modId = "architectury"
type = "required"
versionRange = "[17.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "music_hud.mixins.json"
